{{- $ingress := index .Values "ingress" | default dict }}
{{- if (index $ingress "enabled" | default false) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cooper
spec:
  rules:
    - host: "{{ default (printf "%s.local" .Chart.Name) (index $ingress "host") }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cooper
                port:
                  number: 80
{{- end }}
