apiVersion: v1
kind: Service
metadata:
  name: case-e2e-pr-test-20260304000108
spec:
  selector:
    app.kubernetes.io/name: case-e2e-pr-test-20260304000108
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
