services:
- name: miller
  namespace: demo
  deployTo:
  - local
  generator:
    service:
      template: python-fastapi
    gitops:
      template: helm-service
  overrides:
    image: calavelas/miller:git-786d5f9
- name: mann
  namespace: demo
  deployTo:
  - local
  generator:
    service:
      template: python-fastapi
    gitops:
      template: helm-service
- name: edmund
  namespace: demo
  deployTo:
  - local
  generator:
    service:
      template: python-fastapi
    gitops:
      template: helm-service