services:
- name: demo
  namespace: demo
  deployTo:
  - local
  generator:
    service:
      template: python-fastapi
    gitops:
      template: helm-service
  overrides:
    image: calavelas/demo:0.0.1
    port: 8080
    env:
      LOG_LEVEL: info
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    ingress:
      enabled: true
      host: hello.local