apiVersion: apps/v1
kind: Deployment
metadata:
  name: mann
  labels:
    app.kubernetes.io/name: mann
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mann
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mann
    spec:
      containers:
        - name: mann
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
{{ toYaml .Values.resources | indent 12 }}
