apiVersion: v1
kind: Service
metadata:
  name: demo-pr-0302172827
spec:
  selector:
    app.kubernetes.io/name: demo-pr-0302172827
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
