apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app.kubernetes.io/name: plex
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
    spec:
      containers:
        - name: plex
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
{{- range $name, $value := .Values.env }}
{{- if and $.Values.argocdTokenSecret.enabled (eq $name "PLEX_ARGOCD_TOKEN") }}
{{- else if and $.Values.githubTokenSecret.enabled (eq $name "GITHUB_TOKEN") }}
{{- else }}
            - name: {{ $name }}
              value: {{ $value | quote }}
{{- end }}
{{- end }}
{{- if .Values.argocdTokenSecret.enabled }}
            - name: PLEX_ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.argocdTokenSecret.name | quote }}
                  key: {{ .Values.argocdTokenSecret.key | quote }}
                  optional: {{ .Values.argocdTokenSecret.optional }}
{{- end }}
{{- if .Values.githubTokenSecret.enabled }}
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.githubTokenSecret.name | quote }}
                  key: {{ .Values.githubTokenSecret.key | quote }}
                  optional: {{ .Values.githubTokenSecret.optional }}
{{- end }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
