apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app.kubernetes.io/name: plex
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: plex
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
