apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/calavelas/genesis-platform.git
    targetRevision: main
    path: SVCS/hello-service/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
