apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plt-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-result: "false"
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/calavelas/ENDR.git
    targetRevision: main
    path: KUBE/clusters/space/endurance/gateways
  destination:
    server: https://kubernetes.default.svc
    namespace: plt-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
      - ServerSideDiff=true
      - ServerSideApply=true
