apiVersion: v1
kind: Service
metadata:
  name: caseflow220427
spec:
  selector:
    app.kubernetes.io/name: caseflow220427
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
