apiVersion: v1
kind: Service
metadata:
  name: case-e2e-svcs-order-test
spec:
  selector:
    app.kubernetes.io/name: case-e2e-svcs-order-test
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
