apiVersion: v1
kind: Service
metadata:
  name: endr-case
  labels:
    app.kubernetes.io/name: endr-case
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: endr-case
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
