apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kipp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/calavelas/ENDR.git
    targetRevision: main
    path: SVCS/kipp/chart
    helm:
      valueFiles:
      - values.yaml
      - values-mac-lab.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
