apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mann
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/calavelas/ENDR.git
    targetRevision: main
    path: SVCS/mann/chart
    helm:
      values: |
        ingress:
          enabled: true
          host: mann.k8s.local
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
