replicaCount: 1
image:
  repository: calavelas/plex
  tag: 079e21c
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
httpRoute:
  enabled: true
  name: plex-route
  hostnames:
  - api.k8s.local
  pathPrefix: /
  parentRefs:
  - name: gateway
    namespace: gateway
    sectionName: http
  - name: gateway
    namespace: gateway
    sectionName: https
env:
  IDP_REPO_ROOT: /workspace
  PLEX_ARGOCD_SERVER: http://argocd-server.argocd.svc.cluster.local
  PLEX_ARGOCD_VERIFY_TLS: 'false'
argocdTokenSecret:
  enabled: false
  name: plex-argocd-token
  key: token
  optional: false
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 384Mi
