apiVersion: v1
kind: Service
metadata:
  name: case-e2e-merge-test
spec:
  selector:
    app.kubernetes.io/name: case-e2e-merge-test
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
