apiVersion: v1
kind: Secret
metadata:
  name: gateway-tls-traefik
  namespace: gateway
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIICqDCCAZACCQDbEV/Ht3yHXzANBgkqhkiG9w0BAQsFADAWMRQwEgYDVQQDDAsq
    Lms4cy5sb2NhbDAeFw0yNjAxMTYxMjE3NTNaFw0yNzAxMTYxMjE3NTNaMBYxFDAS
    BgNVBAMMCyouazhzLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEAuY6/tf1dWQPRbvn4OR5jQJU6VlwFYYDSE4BSeTSNQINtWlOmcNHzq8KYcZ1v
    CfVS/veYoOl4OJvrfsoCiVF5jm9MdO2uUC1slrGhvo/QYA2xgZt5o9a+aMTGAKRg
    GfVaofujxyRyR0vYwqfpGbxKnaLwr4Z6yso4q0koYm55x4rmwaA4YMIoxzdAo/LQ
    IE8koUUYrJyE2Rh0A1e550oCMyrejV90cC9osHIdYH+WLMeJE1oV355ZWIe3c/Nh
    hSUAHm8VH+96NUNr8fgJkYfCFDG0LvlQhQlItUOEX6pwm0apTj67EvqLKlUOpAL+
    QHz4d4E+L6Me/ZjbhnpZvlsRbQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQAYcaS1
    AUvYfEt/P3H0qmlsL3Juzg1Wbf+Ahwpl7zyBuwGwWMkYuTbcFpxTLgKj0MZLVW5n
    bvppwoDPRwpz0X2VTlD7+WwZ9oyv3VXeK7oc9F6b6l2qkAr8zFCsSLjfHgvDyqBU
    7nJCW42wSDFZgw9pop9Y+c+uV9olBohBFi3H2mi+xNt+kqItCfdKcR7rWctVL4oT
    tQq4/OoZcGDCfq/vaW7IZt3WvA74hYUcTQlN9ve/SF1/8251ln37zcCMAztCUGBX
    KgZtA8e9XMRkDt604a9i8bIw/C5vWQY6YTGj1fapspi8FW5RM+549Fk6YvmOg6fr
    /OnFRyL6dWKCA0sW
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC5jr+1/V1ZA9Fu
    +fg5HmNAlTpWXAVhgNITgFJ5NI1Ag21aU6Zw0fOrwphxnW8J9VL+95ig6Xg4m+t+
    ygKJUXmOb0x07a5QLWyWsaG+j9BgDbGBm3mj1r5oxMYApGAZ9Vqh+6PHJHJHS9jC
    p+kZvEqdovCvhnrKyjirSShibnnHiubBoDhgwijHN0Cj8tAgTyShRRisnITZGHQD
    V7nnSgIzKt6NX3RwL2iwch1gf5Ysx4kTWhXfnllYh7dz82GFJQAebxUf73o1Q2vx
    +AmRh8IUMbQu+VCFCUi1Q4RfqnCbRqlOPrsS+osqVQ6kAv5AfPh3gT4vox79mNuG
    elm+WxFtAgMBAAECggEBAIdlxzP3nb7PT2oIEn0zVD8S5M+RNAfypNfAAe4ZT5ys
    igWoFkIqoQBK7UuyEg0VKquLZZ683ZGJDGym4PTsM6OgSQzlRhWRH7RSB3DypZ0B
    QO4O0dKgZq4yLzzWtJ0ccDbUVKyCRrUJfjCDr06tG1EtTSz3FvCUYIdzyXkRneDg
    lSkyG6MIiKWwMqteDMxKEotcKSKW5AWb2ujM5lLYpzTybUe8+sTfOGR4pR76978H
    /DvkcvnaZrgJp5sBFAWJ6/y9MaoEUnvHcUKDeP22aPiM+z43/p0IC/X9BJN7cTQ1
    d5QvsXw6RAtsZwOLsbVhOjVF7KEzSyDHrcIANMgi8+0CgYEA8jw5af7ylvllrXBP
    qU2MQ42d8hIsdG+baPBXNSga33FXlrXGwcjH+9jQZfGDDWPq989tow6VGn/AbLLF
    L/FkkFhdBVxotzRIZ+OGbDTzj4NaxcMM6eHDPwxsDc4PlId2kdLNQ7nuxxC70Tif
    nKJ3fwUzKTtEMh2e8OmrjdgnZAMCgYEAxBoKLzC5vDNuLwyY43ShK55+BM3MEWT3
    L8ibuHzfenp3w8qhIGhzBNyNGmmjVtKCebNloxtlkL06ebcuo0ngYzuVzHdi9Mn4
    b3L66y/W2QbZECQTWNj5bT8pjuxwhwlrI/Dw96lTSNup9hZLNFgTV3YKeGF0kSE1
    Cm3Lm2mfEc8CgYEAiT7uGMxGjpvHrDkSKY6yhiPa9aiuX1pM52wlPQz4DNmfEtjz
    QCCOjncNvHTWF+Qg4T85k0VT3au8TtoLN1rB67blHYB6JDMPQy16oBxwU0PNTndw
    /aLYiQR0xG2YDkOiPoT9n/3c+BTXFXfLl2fF5MYBcr8NqId34m/Cr59k0hkCgYAv
    cqF+M4rtJ4CEb8baWhDZDfstzGGQ394TOLW82LH134X04KVFwx/5UCfv+RllW3/o
    VGjGI03azH5GjvUA21IokHU5SLWvxuKOjMJ7f1K7pjWE+0WXHMCVF1BF3Z2IftXm
    l1img9i76zJfcZt2qczcP5pe8C2VI/TCdjhqfQ7Y7wKBgQDVdo87Jn3FwkFmD2NY
    HAoWO/DuBpJkqC0wV3f736G19EpEaiZ/0AtlYarEDA9+rvKBMU2yf+XvsawPYN4W
    6THYaiACtx5suxIkscEENhigtL0gmDP/01AqscRQEXFhPjjjS/pDehuBzUnk+6dY
    bS4/QW4ui9sPxHQuBkkKaMsMVw==
    -----END PRIVATE KEY-----
