apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-cloudflare-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway-cloudflare
      namespace: gateway
  hostnames:
    - "argocd.calavelas.net"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: Access-Control-Allow-Origin
                value: "https://endr.calavelas.net"
              - name: Access-Control-Allow-Methods
                value: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
              - name: Access-Control-Allow-Headers
                value: "Authorization, Content-Type, Accept"
              - name: Access-Control-Allow-Credentials
                value: "true"
      backendRefs:
        - group: ""
          kind: Service
          name: argocd-server
          port: 80
          weight: 1
