apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: endr-api-route
  namespace: endr
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
      sectionName: http
    - name: gateway
      namespace: gateway
      sectionName: https
  hostnames:
    - "api.k8s.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: endr-api
          port: 80
